### ISSUE TITLE
在进入controller中home()时报错

### ISSUE THREAD

**Issue by Jugol7** [Smith-Cruise/Spring-Boot-Security-Thymeleaf-Demo#1]
代码：
UserSS user = (UserSS) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
console：
java.lang.ClassCastException: java.lang.String cannot be cast to com.ss.entity.UserSS
方法getPrincipal()返回的是obj，为什么会报错呢？

**Comment by Smith-Cruise** [comment]
你获取数据的时候保存的是`UserSS`类型吗

**Comment by Jugol7** [comment]
在service中的getUserByUsername()是返回的是UserSS类型

**Comment by Smith-Cruise** [comment]
如果和我的示例差不多应该是没有问题的，你试试不从`SecurityContextHolder`中获取看看，用另外的方法。

**Comment by Jugol7** [comment]
好的，我试试，谢谢你
